[features]
seeds = false
skip-lint = false
[programs.localnet]
token_contract = "EGLQX6HoYfPxnNd8LSQh4taqPFLXhAjeUxtrU65Zn8TU"

[registry]
url = "http://localhost:8899"

[provider]
cluster = "Localnet"
wallet = "/home/ashutosh/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
